Harden GTFS parsing
nickolasclarke/dispatch pull request #45
Opened 2020-03-12 22:56 UTC by r-barnes

2020-03-12 23:04 UTC, nickolasclarke commented on src/parse_gtfs.py
>    bus_routes = gtfs.routes[gtfs.routes['route_type'] == 3]['route_id']
this will be critical for many routes. I'll open an issue.

2020-03-12 23:07 UTC, nickolasclarke requested changes

2020-03-12 23:07 UTC, nickolasclarke commented on src/parse_gtfs.py
> +  # if not (f'start_{colname}' in trips.columns and
should be removed if not required.

2020-03-13 16:54 UTC, r-barnes commented on src/parse_gtfs.py
> +  # if not (f'start_{colname}' in trips.columns and
Fixed.

2020-03-13 17:23 UTC, nickolasclarke approved these changes

2020-03-13 17:30 UTC, merged